### ISSUE TITLE
Randomly retrieves empty values

### ISSUE THREAD

**Issue by rdlmda** [virtualzone/docker-container-stats#3]
For some reason, only a few of the stats datapoints will have data. The vast majority is empty.

Here's my `docker-compose` file:
```
version: '3.6'
services:
  stats:
    image: weweave/docker-container-stats
    container_name: 'stats'
    labels:
      - 'traefik.docker.network=web'
      - 'traefik.enable=true'
      - 'traefik.basic.frontend.rule=[REDACTED]'
      - 'traefik.basic.port=8080'
      - 'traefik.basic.protocol=http'
      - 'traefik.frontend.auth.basic.users=[REDACTED]'
    volumes:
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './data:/opt/docker-stats/db'
    networks:
      - web

networks:
  web:
    external: true
```
